
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Construct DATABASE_URL from individual environment variables if DATABASE_URL is not set
const getDatabaseUrl = () => {
  const dbUrl = env("DATABASE_URL");
  if (dbUrl) return dbUrl;

  const host = env("DB_HOST");
  const port = env("DB_PORT");
  const user = env("DB_USER");
  const password = env("DB_PASSWORD");
  const database = env("DB_NAME");

  return `mysql://${user}:${password}@${host}:${port}/${database}`;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: getDatabaseUrl(),
  },
});
